### ISSUE TITLE
Downloaded FFMPEG/FFPROBE not executable

### ISSUE THREAD

**Issue by porncloud** [boi123212321/porn-manager#130]
Not sure if this is a "me" issue, or a bug, but when I run the linux version of the app, it downloads the FFMPEG/FFPROBE but doesn't make them executable, so when you run the app you get an error:-

`(node:22534) UnhandledPromiseRejectionWarning: Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:508:9)
    at childProcess.spawn (pkg/prelude/bootstrap.js:1413:27)
    at /snapshot/porn-manager/node_modules/fluent-ffmpeg/lib/ffprobe.js:155:21
    at FfmpegCommand.module.exports.proto._getFfprobePath (/snapshot/porn-manager/node_modules/fluent-ffmpeg/lib/capabilities.js:144:14)
    at FfmpegCommand.module.exports.proto.ffprobe (/snapshot/porn-manager/node_modules/fluent-ffmpeg/lib/ffprobe.js:141:10)
    at Function.FfmpegCommand.ffprobe (/snapshot/porn-manager/node_modules/fluent-ffmpeg/lib/fluent-ffmpeg.js:221:20)
    at Queue.<anonymous> (/snapshot/porn-manager/build/queue/index.js:81:45)
    at Generator.next (<anonymous>)
    at __awaiter (/snapshot/porn-manager/build/queue/index.js:8:71)
(node:22534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

If you chmod +x the two files then it runs ok?

**Comment by boi123212321** [comment]
```
chmod 777 ffmpeg
chmod 777 ffprobe
```

Should probably at that to the code...
