### ISSUE TITLE
Queue processing stopped when encountering a bad file

### ISSUE THREAD

**Issue by tltgt** [boi123212321/porn-manager#189]
Version: 0.9.1 linux version downloaded from https://github.com/boi123212321/porn-manager/releases/tag/0.9.1

Whilst scanning for video files, it encountered a problem with a file and after that it didn't continue on to the next file.

Note that this file is not actually a video file. It's a file created by Mac OSX to store some metadata over SMB NAS.

Expected behavior: it should just move on to the next file

```
$ ./porn-manager
  porn:message Check https://github.com/boi123212321/porn-manager for discussion & updates +0ms
  porn:message Max. memory: 8121 MB +3ms
? Enter password [hidden]
  porn:warn Creating backup in backups/k4zo0a1t... +0ms
✔ Integrity check done.
Server running on Port 3001
  porn:warn Scanning folders... +513ms
  porn:warn Not generating previews because GENERATE_PREVIEWS is disabled. +2ms
  porn:warn Queued 0 new videos. +18s
  porn:warn Reading images on import is disabled. +2ms
  porn:warn Added 0 new images +0ms
  porn:message Processing /some/path/._somefilename.mp4... +20s
Error: ffprobe exited with code 1
ffprobe version N-48944-g9b069eb14e-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 28.100 / 56. 28.100
  libavcodec     58. 52.102 / 58. 52.102
  libavformat    58. 27.103 / 58. 27.103
  libavdevice    58.  7.100 / 58.  7.100
  libavfilter     7. 54.101 /  7. 54.101
  libswscale      5.  4.101 /  5.  4.101
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x698ca40] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x698ca40] moov atom not found
/some/path/._somefilename.mp4: Invalid data found when processing input

    at ChildProcess.<anonymous> (/snapshot/porn-manager/node_modules/fluent-ffmpeg/lib/ffprobe.js:233:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
  porn:error Error ffprobing file - perhaps a permission problem? +0ms
  porn:error Error: Error
  porn:error     at Queue.<anonymous> (/snapshot/porn-manager/build/queue/index.js:110:23)
  porn:error     at Generator.throw (<anonymous>)
  porn:error     at rejected (/snapshot/porn-manager/build/queue/index.js:6:65)
  porn:error     at <anonymous>
  porn:error     at process._tickCallback (internal/process/next_tick.js:189:7) +0ms
  porn:error Error processing scene +0ms
```

**Comment by tltgt** [comment]
Shouldn't line 262 be moved outside the catch?
`await database.remove(this.store, { _id: head._id });`
